docs: about evm memory limit on ckb-vm
nervosnetwork/godwoken-polyjuice pull request #147
Opened 2022-04-28 02:57 UTC by magicalne

Add docs about why some eth contracts could run into errors due to memory limit.

2022-04-28 16:44 UTC, TheWaWaR requested changes

2022-04-28 16:44 UTC, TheWaWaR commented on docs/EVM-compatible.md
> +In ckb-vm, 3MB for code space and 1MB for stack space. See more details in [here](https://github.com/nervosnetwork/riscv-newlib/blob/00c6ae3c481bc62b4ac016b3e86c508cdf2e68d2/libgloss/riscv/sys_sbrk.c
`3MB for code space` => `3MB for heap space`

2022-04-28 17:03 UTC, ashleewang888 commented on docs/EVM-compatible.md
> +Polyjuice runs EVM on the ckb-vm. Although there is no limit on memory usage of EVM(well, EVM does have a limit on stack depth which is 1024), ckb-vm can only use 4MB memory at most for now.
Polyjuice runs EVM on ckb-vm. While EVM has no limit on memory usage (despite the limit of 1024 on stack depth for EVM), ckb-vm can use a maximum of 4MB of memory for now.

2022-04-28 17:03 UTC, ashleewang888 commented on docs/EVM-compatible.md
> +In ckb-vm, 3MB for code space and 1MB for stack space. See more details in [here](https://github.com/nervosnetwork/riscv-newlib/blob/00c6ae3c481bc62b4ac016b3e86c508cdf2e68d2/libgloss/riscv/sys_sbrk.c
Of which, 3MB .......

2022-04-28 17:07 UTC, ashleewang888 commented on docs/EVM-compatible.md
> +It means that, for some contracts, which consume a lot of memory or have deep call stacks, those contracts could be not compatible on the ckb-vm.
For some contracts that consume a lot of memory or that have deep call stacks, this may indicate a potential incompatibility on ckb-vm.

2022-04-29 02:15 UTC, gpBlockchain approved these changes

2022-04-29 02:57 UTC, Flouse approved these changes

2022-04-29 03:34 UTC, TheWaWaR approved these changes

2022-04-29 06:23 UTC, ashleewang888 approved these changes

2022-04-29 06:24 UTC, merged