fix: get code, code hash and code size from an unregistered address
nervosnetwork/godwoken-polyjuice pull request #167
Opened 2022-06-16 03:38 UTC by magicalne

Handling get_code, get_code_size, and get_code_hash for the unregistered addresses instead of throwing an error.

2022-06-19 09:58 UTC, Flouse requested changes
Please fix the conflicts.

2022-06-27 09:32 UTC, Flouse commented on c/polyjuice_utils.h
>  }
Delete this line since it is unreachable.

2022-06-27 09:37 UTC, Flouse commented on polyjuice-tests/src/test_cases/absent_address.rs
> +    //call getBalance("0xdB81D2b8154A10C6f25bC2a9225F403D954D0B65")
```suggestion
    // 0xdB81D2b8154A10C6f25bC2a9225F403D954D0B65 is an unregistered eth_address.
    // call getBalance("0xdB81D2b8154A10C6f25bC2a9225F403D954D0B65")
```

2022-06-27 09:43 UTC, Flouse commented on polyjuice-tests/src/test_cases/absent_address.rs
> +    let mut target = [0u8; 64];
```suggestion
    // expected output: { "0": "bytes: 0x"}
    let mut target = [0u8; 64];
```

2022-06-27 09:43 UTC, Flouse submitted a review, later dismissed

2022-06-27 09:51 UTC, TheWaWaR submitted a review, later dismissed

2022-06-27 10:17 UTC, zeroqn submitted a review, later dismissed

2022-06-28 03:12 UTC, Flouse approved these changes

2022-06-28 03:13 UTC, merged